import org.gradle.api.tasks.Sync
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.OutputDirectory

abstract class GeneratedHyperLyricSync : Sync() {
    @get:OutputDirectory
    abstract val generatedDirectory: DirectoryProperty

    init {
        into(generatedDirectory)
    }
}

plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.kotlin.serialization)
    id("kotlin-parcelize")
}

@Suppress("UnstableApiUsage")
android {
    namespace = "com.lidesheng.hyperlyric"
    buildToolsVersion = "37.0.0"
    compileSdk {
        version = release(37) {
            minorApiLevel = 0
        }
    }

    defaultConfig {
        minSdk = 36
        buildConfigField("boolean", "ONLINE_FEATURES_ENABLED", "true")
        // These fields are generated by HyperLyric's application module. The port is a library,
        // so retain the upstream version identity while binding package-sensitive calls to this host.
        buildConfigField("int", "VERSION_CODE", "1937")
        buildConfigField("String", "VERSION_NAME", "\"7.2\"")
        buildConfigField("String", "APPLICATION_ID", "\"io.github.superisland\"")
    }

    buildFeatures {
        aidl = true
        buildConfig = true
        compose = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
}

dependencies {
    implementation(project(":source-lyric"))
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.constraintlayout.compose)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.palette.ktx)
    implementation(libs.androidx.compose.animation.graphics)
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.compose.foundation)
    implementation(libs.hiddenapibypass)
    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.libxposed.service)
    implementation(libs.miuix.blur)
    implementation(libs.miuix.icons)
    implementation(libs.miuix.nav)
    implementation(libs.miuix.preference)
    implementation(libs.miuix.ui)
    implementation(libs.okhttp)
    implementation(libs.reorderable)
    implementation(libs.retrofit)
    implementation(libs.retrofit.kotlinx.serialization.converter)
    implementation(libs.shizuku.api)
    implementation(libs.shizuku.provider)
    implementation(libs.superlyric.api)
    implementation(libs.lyricon.subscriber)
    implementation(libs.daimajia.animations) { artifact { type = "aar" } }
    implementation(libs.daimajia.easing) { artifact { type = "aar" } }
    compileOnly(libs.libxposed.api)
}

val hyperLyricReferenceCommit = "03ca5f4e92e78ec0924ac13ecee4a36640fa933a"
val superIslandUpstreamsDir =
    providers.gradleProperty("superIslandUpstreamsDir")
        .orElse(providers.environmentVariable("SUPER_ISLAND_UPSTREAMS_DIR"))
        .orElse("${System.getProperty("user.home")}/.cache/super-island/upstreams")
        .map(::file)
val hyperLyricCheckout = superIslandUpstreamsDir.get().resolve("HyperLyric")
val hyperLyricMainRoot = hyperLyricCheckout.resolve("app/src/main")
val hyperLyricSourceRoot = hyperLyricMainRoot.resolve("java")
val hyperLyricOnlineSourceRoot = hyperLyricCheckout.resolve("app/src/online/java")
val hyperLyricPluginApiRoot = hyperLyricCheckout.resolve("Plugins/api/src/main/kotlin")
val hyperLyricPluginApiPackageRoot =
    hyperLyricPluginApiRoot.resolve("com/lidesheng/hyperlyric")
val hyperLyricPluginModuleRoots =
    hyperLyricCheckout.resolve("Plugins/modules")
        .listFiles()
        ?.map { it.resolve("src/main/java") }
        ?.filter { it.isDirectory }
        ?.sortedBy { it.invariantSeparatorsPath }
        .orEmpty()
val hyperLyricExcludesFile = layout.projectDirectory.file("hyperlyric-excludes.txt")
val hyperLyricExcludedSources =
    hyperLyricExcludesFile.asFile.readLines()
        .map(String::trim)
        .filter { it.isNotEmpty() && !it.startsWith("#") }
        .toSet()
// Super Island owns the only user-facing settings surface. These are HyperLyric application
// lifecycle/configuration classes, not its SystemUI runtime, so they must never be generated.
val hyperLyricApplicationOnlySources = setOf(
    "common/PrefsBridge.kt",
    "lyric/ConfigRepository.kt",
    "root/RootApplication.kt",
    "utils/BackupRestoreManager.kt",
    "utils/LyricProviderManager.kt",
)
// Every generated upstream source must remain byte-for-byte identical unless this small,
// audited set needs the current module's LSPosed service or preferences owner.
val hyperLyricPortAdaptedSources = setOf(
    "plugin/app/PluginRepository.kt",
    "root/HookEntry.kt",
    "root/UnlockIslandWhitelist.kt",
    "root/island/effects/album/IslandAlbumCoverStyleHooker.kt",
    "root/island/effects/color/IslandMusicWaveColorHooker.kt",
    "root/island/effects/glow/HookIslandGlow.kt",
    "utils/LogManager.kt",
)
val hyperLyricAppUiSourcePrefix = "ui/"
fun isHyperLyricPortExcludedSource(relativePath: String): Boolean =
    relativePath in hyperLyricExcludedSources ||
        relativePath in hyperLyricApplicationOnlySources ||
        relativePath.startsWith(hyperLyricAppUiSourcePrefix)
val hyperLyricGeneratedSourceDir = layout.buildDirectory.dir("generated/source/hyperlyric")
val hyperLyricGeneratedAidlDir = layout.buildDirectory.dir("generated/aidl/hyperlyric")
val hyperLyricGeneratedResDir = layout.buildDirectory.dir("generated/res/hyperlyric")

val verifyHyperLyricReference = tasks.register("verifyHyperLyricReference") {
    group = "verification"
    description = "Verifies the fixed HyperLyric checkout before source and values generation."
    dependsOn(rootProject.tasks.named("verifyPinnedUpstreams"))
    inputs.file(hyperLyricExcludesFile)
    inputs.dir(hyperLyricCheckout)
    doLast {
        val commit = providers.exec {
            commandLine("git", "-C", hyperLyricCheckout.absolutePath, "rev-parse", "HEAD")
        }.standardOutput.asText.get().trim()
        check(commit == hyperLyricReferenceCommit) {
            "HyperLyric reference mismatch: expected $hyperLyricReferenceCommit, got $commit"
        }
        check(hyperLyricExcludedSources.size == 10) {
            "HyperLyric exclusions changed without review: $hyperLyricExcludedSources"
        }
        check(
            hyperLyricExcludedSources.all {
                hyperLyricSourceRoot.resolve("com/lidesheng/hyperlyric/$it").isFile
            },
        ) {
            "HyperLyric exclusion is not a source file: $hyperLyricExcludedSources"
        }
        check(
            hyperLyricApplicationOnlySources.all {
                hyperLyricSourceRoot.resolve("com/lidesheng/hyperlyric/$it").isFile
            },
        ) {
            "HyperLyric application-only source is not a source file: $hyperLyricApplicationOnlySources"
        }
    }
}

val generateHyperLyricPortSource = tasks.register<GeneratedHyperLyricSync>("generateHyperLyricPortSource") {
    dependsOn(verifyHyperLyricReference)
    generatedDirectory.set(hyperLyricGeneratedSourceDir)
    from(hyperLyricSourceRoot) {
        include("**/*.kt")
        (hyperLyricExcludedSources + hyperLyricApplicationOnlySources).forEach { excluded ->
            exclude("com/lidesheng/hyperlyric/$excluded")
        }
        exclude("com/lidesheng/hyperlyric/ui/**")
    }
    // HyperLyric's default app flavor is online; use that exact source set rather than a local
    // lyric-provider substitute.
    from(hyperLyricOnlineSourceRoot) {
        include("**/*.kt")
    }
    from(hyperLyricPluginApiPackageRoot) {
        include("**/*.kt")
        into("com/lidesheng/hyperlyric")
    }
    hyperLyricPluginModuleRoots.forEach { pluginModuleRoot ->
        from(pluginModuleRoot) {
            include("**/*.kt")
        }
    }
    doLast {
        val generatedRoot = hyperLyricGeneratedSourceDir.get().asFile
        val sourceRoot = hyperLyricSourceRoot.resolve("com/lidesheng/hyperlyric")
        val expectedSources = sourceRoot.walkTopDown()
            .filter { it.isFile && it.extension == "kt" }
            .map { it.relativeTo(sourceRoot).invariantSeparatorsPath }
            .filterNot(::isHyperLyricPortExcludedSource)
            .toMutableSet()
            .apply {
                addAll(
                    hyperLyricOnlineSourceRoot.resolve("com/lidesheng/hyperlyric").walkTopDown()
                        .filter { it.isFile && it.extension == "kt" }
                        .map { it.relativeTo(hyperLyricOnlineSourceRoot.resolve("com/lidesheng/hyperlyric")).invariantSeparatorsPath },
                )
                addAll(
                    hyperLyricPluginApiPackageRoot.walkTopDown()
                        .filter { it.isFile && it.extension == "kt" }
                        .map { it.relativeTo(hyperLyricPluginApiPackageRoot).invariantSeparatorsPath },
                )
                hyperLyricPluginModuleRoots.forEach { pluginModuleRoot ->
                    val packageRoot = pluginModuleRoot.resolve("com/lidesheng/hyperlyric")
                    addAll(
                        packageRoot.walkTopDown()
                            .filter { it.isFile && it.extension == "kt" }
                            .map { it.relativeTo(packageRoot).invariantSeparatorsPath },
                    )
                }
                // The only local source in this module is the narrow LSPosed-service adapter used
                // by the directly imported PluginRepository. It replaces RootApplication's app
                // lifecycle binding without importing any upstream App settings or navigation.
                add("root/PortXposedServiceBridge.kt")
            }
        generatedRoot.resolve("com/lidesheng/hyperlyric/root/PortXposedServiceBridge.kt").apply {
            parentFile.mkdirs()
            writeText(
                """package com.lidesheng.hyperlyric.root

import io.github.libxposed.service.XposedService
import io.github.libxposed.service.XposedServiceHelper
import java.util.concurrent.CopyOnWriteArraySet

/** Minimal replacement for RootApplication's App-process service holder. */
object PortXposedServiceBridge {
    private val services = CopyOnWriteArraySet<XposedService>()

    @Volatile
    private var started = false

    fun serviceOrNull(): XposedService? {
        if (!started) synchronized(this) {
            if (!started) {
                XposedServiceHelper.registerListener(
                    object : XposedServiceHelper.OnServiceListener {
                        override fun onServiceBind(service: XposedService) {
                            services += service
                        }

                        override fun onServiceDied(service: XposedService) {
                            services -= service
                        }
                    },
                )
                started = true
            }
        }
        return services.firstOrNull()
    }
}
""",
            )
        }
        val generatedSources = generatedRoot.resolve("com/lidesheng/hyperlyric").walkTopDown()
            .filter { it.isFile && it.extension == "kt" }
            .map { it.relativeTo(generatedRoot.resolve("com/lidesheng/hyperlyric")).invariantSeparatorsPath }
            .toSet()
        check(generatedSources == expectedSources) {
            "HyperLyric generated source set changed; missing=${expectedSources - generatedSources}, " +
                "unexpected=${generatedSources - expectedSources}"
        }
        check(
            (hyperLyricExcludedSources + hyperLyricApplicationOnlySources).none {
                generatedRoot.resolve("com/lidesheng/hyperlyric/$it").exists()
            },
        ) {
            "Excluded HyperLyric source was generated"
        }
        check(generatedSources.none { it.startsWith(hyperLyricAppUiSourcePrefix) }) {
            "HyperLyric App UI source was generated"
        }
        val visualResourceReferences = generatedRoot.walkTopDown()
            .filter { it.isFile && it.extension == "kt" }
            .filter { source ->
                Regex("""R\\.(drawable|mipmap|xml|font|raw)\\.""").containsMatchIn(source.readText())
            }
            .map { it.relativeTo(generatedRoot).invariantSeparatorsPath }
            .toList()
        check(visualResourceReferences.isEmpty()) {
            "HyperLyric source still references a non-portable visual resource: $visualResourceReferences"
        }

        // Explicit feature removals approved for this port: Live Update and its Focus-whitelist
        // hook must not remain reachable after their source files are excluded.
        val hookEntry = generatedRoot.resolve("com/lidesheng/hyperlyric/root/HookEntry.kt")
        val originalHookEntry = hookEntry.readText()
        val hookCall = """                UnlockFocusWhitelist.hook(this, param.defaultClassLoader)
"""
        check(originalHookEntry.contains(hookCall)) { "HyperLyric HookEntry whitelist call changed" }
        val withoutFocusWhitelist = originalHookEntry.replace(hookCall, "")
        val runtimeField = """    private var runtimeApp: Application? = null
"""
        check(withoutFocusWhitelist.contains(runtimeField)) {
            "HyperLyric HookEntry runtime field changed"
        }
        val portRuntimeField = """    private var portHostModule: XposedModule? = null
"""
        val companionClose = """        )
    }

    private var _prefs: android.content.SharedPreferences? = null
"""
        check(withoutFocusWhitelist.contains(companionClose)) {
            "HyperLyric HookEntry companion boundary changed"
        }
        val portBinding = """        )

        private val portSystemUiHookedClassLoaders = java.util.Collections.synchronizedSet(
            java.util.Collections.newSetFromMap(java.util.WeakHashMap<ClassLoader, Boolean>())
        )

        /** Supplies the host adapter before the unmodified upstream load chain runs. */
        @JvmStatic
        fun preparePortRuntime(
            module: XposedModule,
            preferences: android.content.SharedPreferences,
            classLoader: ClassLoader
        ) {
            val runtime = instance ?: HookEntry().also { instance = it }
            runtime.portHostModule = module
            runtime._prefs = preferences
            HookLogger.module = module
            installPortSystemUiRuntime(module, classLoader)
        }

        /**
         * Runs the full SystemUI branch from HookEntry.onPackageLoaded with the existing
         * Super Island module as the only hook-handle owner.
         */
        @JvmStatic
        fun installPortSystemUiRuntime(module: XposedModule, classLoader: ClassLoader) {
            val runtime = instance ?: return
            if (!portSystemUiHookedClassLoaders.add(classLoader)) return

            StatusBarTextColorHooker.setTextColorChangedListener {
                BaseIslandRenderer.updateTextColors()
            }
            StatusBarTextColorHooker.hook(module, classLoader)
            MediaCardRuntimeConfig.load(runtime.prefs)
            MediaCardConfigurationRefreshHooker.hook(module, classLoader)
            MediaProgressStyleHooker.hook(module, classLoader)
            MediaCardElementBehaviorHooker.hook(module, classLoader)
            IslandExpandedMediaAmbientFlowHooker.hook(module, classLoader)
            IslandExpandedMediaLayoutHooker.hook(module, classLoader)
            NotificationMediaAmbientFlowHooker.hook(module, classLoader)
            NotificationMediaCoverStyleHooker.hook(module, classLoader)
            if (MediaCardRuntimeConfig.current.notification.cardSwitcherEnabled) {
                NotificationMediaSingleCardSwitcherHooker.hook(module, classLoader)
            } else {
                HookLogger.d(TAG, "通知中心多媒体卡片切换功能未启用，跳过媒体卡片切换 Hook")
            }
            try {
                UnlockIslandWhitelist.hook(module, classLoader)
            } catch (e: Exception) {
                if (e is ClassNotFoundException || e is NoSuchMethodException) {
                    HookLogger.w(TAG, "此系统版本不支持超级岛下拉小窗白名单")
                } else {
                    HookLogger.e(TAG, "超级岛下拉小窗白名单注入失败", e)
                }
            }
            activeMode = runtime.prefs.getInt(
                RootConstants.KEY_HOOK_LYRIC_MODE,
                RootConstants.DEFAULT_HOOK_LYRIC_MODE
            )

            // 劫持 Application.onCreate 以初始化 Lyricon Receiver 所需的环境
            try {
                val appClass = classLoader.loadClass("android.app.Application")
                val onCreateMethod = appClass.getDeclaredMethod("onCreate")
                module.deoptimize(onCreateMethod)
                module.hook(onCreateMethod).intercept(AppCreateHooker())
            } catch (e: Exception) {
                if (e is ClassNotFoundException || e is NoSuchMethodException) {
                    HookLogger.w(TAG, "跳过生命周期 Hook: target=Application.onCreate")
                } else {
                    HookLogger.e(
                        TAG,
                        "安装生命周期 Hook 失败: target=Application.onCreate",
                        e
                    )
                }
            }

            // 核心：拦截 ClassLoader 构造，以捕捉 miui.systemui.plugin 等动态加载的插件
            try {
                val clClass = Class.forName("dalvik.system.BaseDexClassLoader")
                for (constructor in clClass.declaredConstructors) {
                    module.deoptimize(constructor)
                    module.hook(constructor).intercept(runtime.ClassLoaderHooker())
                }
            } catch (e: Exception) {
                if (e is ClassNotFoundException || e is NoSuchMethodException) {
                    HookLogger.w(TAG, "跳过插件加载 Hook: target=BaseDexClassLoader")
                } else {
                    HookLogger.e(
                        TAG,
                        "安装插件加载 Hook 失败: target=BaseDexClassLoader",
                        e
                    )
                }
            }
        }
    }

    private var _prefs: android.content.SharedPreferences? = null
"""
        val withPortRuntime = withoutFocusWhitelist
            .replace(runtimeField, runtimeField + portRuntimeField)
            .replace(companionClose, portBinding)
            .replace(
                """            pluginRuntime = runCatching {
                PluginRuntime(this, app).also { it.loadEnabledPlugins() }
""",
                """            pluginRuntime = runCatching {
                PluginRuntime(portHostModule ?: this, app).also { it.loadEnabledPlugins() }
""",
            )
            .replace(
                """                SystemUIHookRegistry.hook(this@HookEntry, cl, lyricsOnly = lyricsOnly)
""",
                """                SystemUIHookRegistry.hook(portHostModule ?: this@HookEntry, cl, lyricsOnly = lyricsOnly)
""",
            )
            .replace(
                """            if (SystemUiEnhancementGate.isEnabled()) {
                sourceManager?.start()
            }
""",
                """            if (SystemUiEnhancementGate.isEnabled() &&
                prefs.getString(
                    RootConstants.KEY_HOOK_LYRIC_SOURCE,
                    RootConstants.DEFAULT_HOOK_LYRIC_SOURCE
                ) != "media_fallback"
            ) {
                sourceManager?.start()
            }
""",
            )
            .replace(
                """                            Handler(Looper.getMainLooper()).post {
                                val manager = sourceManager
                                manager?.switchSource(newSourceId)
                                val activeSourceId = manager?.getActiveSource()?.id
                                if (activeSourceId == newSourceId) {
                                    HookLogger.i(TAG, "歌词源切换完成: source=${'$'}newSourceId")
                                }
                            }
""",
                """                            Handler(Looper.getMainLooper()).post {
                                val manager = sourceManager
                                if (newSourceId == "media_fallback") {
                                    manager?.stop()
                                    HookLogger.i(TAG, "歌词源切换完成: source=${'$'}newSourceId")
                                } else {
                                    manager?.switchSource(newSourceId)
                                    val activeSourceId = manager?.getActiveSource()?.id
                                    if (activeSourceId == newSourceId) {
                                        HookLogger.i(TAG, "歌词源切换完成: source=${'$'}newSourceId")
                                    }
                                }
                            }
""",
            )
            .replace(
                """        if (enabled) {
            sourceManager?.start()
            IslandSettingsRefreshCoordinator.request()
""",
                """        if (enabled) {
            if (prefs.getString(
                    RootConstants.KEY_HOOK_LYRIC_SOURCE,
                    RootConstants.DEFAULT_HOOK_LYRIC_SOURCE
                ) != "media_fallback"
            ) {
                sourceManager?.start()
            }
            IslandSettingsRefreshCoordinator.request()
""",
            )
        check(withPortRuntime.contains("preparePortRuntime(")) {
            "HyperLyric HookEntry port binding was not generated"
        }
        check(withPortRuntime.contains("PluginRuntime(portHostModule ?: this, app)")) {
            "HyperLyric PluginRuntime host binding changed"
        }
        check(withPortRuntime.contains("SystemUIHookRegistry.hook(portHostModule ?: this@HookEntry")) {
            "HyperLyric ClassLoader hook host binding changed"
        }
        hookEntry.writeText(withPortRuntime)

        // These upstream effect owners receive the host's registered XposedModule. In this port
        // that instance is SuperIslandXposedModule rather than HookEntry, while HookEntry.instance
        // remains the upstream owner of the bound RemotePreferences. Keep every effect algorithm
        // intact and adapt only that host-instance lookup.
        fun replacePortPreferenceOwner(
            relativePath: String,
            original: String,
            replacement: String,
        ) {
            val file = generatedRoot.resolve("com/lidesheng/hyperlyric/$relativePath")
            val source = file.readText()
            check(source.contains(original)) {
                "HyperLyric port preference owner changed: $relativePath"
            }
            file.writeText(source.replace(original, replacement))
        }
        replacePortPreferenceOwner(
            relativePath = "root/island/effects/album/IslandAlbumCoverStyleHooker.kt",
            original = "get() = (module as? HookEntry)?.prefs",
            replacement = "get() = HookEntry.instance?.prefs",
        )
        replacePortPreferenceOwner(
            relativePath = "root/island/effects/color/IslandMusicWaveColorHooker.kt",
            original = "get() = (module as? HookEntry)?.prefs",
            replacement = "get() = HookEntry.instance?.prefs",
        )
        replacePortPreferenceOwner(
            relativePath = "root/island/effects/glow/HookIslandGlow.kt",
            original = "get() = if (::module.isInitialized) (module as? HookEntry)?.prefs else null",
            replacement = "get() = if (::module.isInitialized) HookEntry.instance?.prefs else null",
        )
        replacePortPreferenceOwner(
            relativePath = "root/UnlockIslandWhitelist.kt",
            original = "val prefs = (module as HookEntry).prefs",
            replacement = "val prefs = HookEntry.instance?.prefs ?: return",
        )
        replacePortPreferenceOwner(
            relativePath = "root/UnlockIslandWhitelist.kt",
            original = "val prefs = (module as? HookEntry)?.prefs ?: return",
            replacement = "val prefs = HookEntry.instance?.prefs ?: return",
        )

        val pluginRepository = generatedRoot.resolve(
            "com/lidesheng/hyperlyric/plugin/app/PluginRepository.kt",
        )
        val originalPluginRepository = pluginRepository.readText()
        val rootApplicationService =
            "com.lidesheng.hyperlyric.root.RootApplication.xposedService"
        check(originalPluginRepository.contains(rootApplicationService)) {
            "HyperLyric PluginRepository service bridge changed"
        }
        pluginRepository.writeText(
            originalPluginRepository.replace(
                rootApplicationService,
                "com.lidesheng.hyperlyric.root.PortXposedServiceBridge.serviceOrNull()",
            ),
        )

        val logManager = generatedRoot.resolve("com/lidesheng/hyperlyric/utils/LogManager.kt")
        val originalLogManager = logManager.readText()
        val readSection = "    // ========================= 读取 ========================="
        check(originalLogManager.contains(readSection)) {
            "HyperLyric LogManager read section changed"
        }
        // Log writing is used by the imported online/runtime code. Reading and rendering those
        // entries belongs to HyperLyric's App log page, which this port does not generate.
        logManager.writeText(
            originalLogManager
                .substringBefore(readSection)
                .replace("import com.lidesheng.hyperlyric.ui.page.log.LogEntry\n", "")
                .trimEnd() + "\n}\n",
        )

        val unexpectedMainSourceDifferences = sourceRoot.walkTopDown()
            .filter { it.isFile && it.extension == "kt" }
            .map { source ->
                val relativePath = source.relativeTo(sourceRoot).invariantSeparatorsPath
                relativePath to source
            }
            .filterNot { (relativePath, _) -> isHyperLyricPortExcludedSource(relativePath) }
            .filterNot { (relativePath, _) -> relativePath in hyperLyricPortAdaptedSources }
            .filter { (relativePath, source) ->
                generatedRoot.resolve("com/lidesheng/hyperlyric/$relativePath").readText() != source.readText()
            }
            .map { (relativePath, _) -> relativePath }
            .toList()
        check(unexpectedMainSourceDifferences.isEmpty()) {
            "HyperLyric source changed outside the audited host adapters: " +
                unexpectedMainSourceDifferences
        }

    }
}

val generateHyperLyricPortAidl = tasks.register<GeneratedHyperLyricSync>("generateHyperLyricPortAidl") {
    dependsOn(verifyHyperLyricReference)
    generatedDirectory.set(hyperLyricGeneratedAidlDir)
    from(hyperLyricMainRoot.resolve("aidl"))
}

val generateHyperLyricPortResources = tasks.register<GeneratedHyperLyricSync>("generateHyperLyricPortResources") {
    dependsOn(verifyHyperLyricReference)
    generatedDirectory.set(hyperLyricGeneratedResDir)
    // HyperLyric images, launcher icons, media-preview artwork, and App-page animation assets are
    // deliberately not packaged. Values are the only non-visual resources required to compile the
    // directly ported source; lyric-island runtime rendering is code-driven and needs no static art.
    from(hyperLyricMainRoot.resolve("res")) {
        include("values*/**/*.xml")
    }
    doLast {
        val expected = hyperLyricMainRoot.resolve("res").walkTopDown()
            .filter { it.isFile }
            .filter { it.relativeTo(hyperLyricMainRoot.resolve("res")).invariantSeparatorsPath.startsWith("values") }
            .map { it.relativeTo(hyperLyricMainRoot.resolve("res")).invariantSeparatorsPath }
            .toSet()
        val generated = hyperLyricGeneratedResDir.get().asFile.walkTopDown()
            .filter { it.isFile }
            .map { it.relativeTo(hyperLyricGeneratedResDir.get().asFile).invariantSeparatorsPath }
            .toSet()
        check(generated == expected) {
            "HyperLyric generated values changed; missing=${expected - generated}, " +
                "unexpected=${generated - expected}"
        }
        check(generated.none { it.startsWith("drawable") || it.startsWith("mipmap") || it.startsWith("xml") }) {
            "HyperLyric visual or manifest resource was generated: $generated"
        }
    }
}

// AGP 9's library SourceSet DSL has an incompatible runtime implementation. Register these
// generated directories through the supported variant source API so every variant is wired to
// the fixed upstream generation tasks without writing generated code into the worktree.
androidComponents {
    onVariants(selector().all()) { variant ->
        variant.sources.java?.addGeneratedSourceDirectory(
            generateHyperLyricPortSource,
            GeneratedHyperLyricSync::generatedDirectory,
        )
        variant.sources.kotlin?.addGeneratedSourceDirectory(
            generateHyperLyricPortSource,
            GeneratedHyperLyricSync::generatedDirectory,
        )
        variant.sources.aidl?.addGeneratedSourceDirectory(
            generateHyperLyricPortAidl,
            GeneratedHyperLyricSync::generatedDirectory,
        )
        variant.sources.res?.addGeneratedSourceDirectory(
            generateHyperLyricPortResources,
            GeneratedHyperLyricSync::generatedDirectory,
        )
    }
}

tasks.matching { it.name == "preBuild" }.configureEach {
    dependsOn(
        generateHyperLyricPortSource,
        generateHyperLyricPortAidl,
        generateHyperLyricPortResources,
    )
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    dependsOn(generateHyperLyricPortSource)
}
