import org.gradle.api.tasks.Sync
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.OutputDirectory

abstract class GeneratedHyperLyricSync : Sync() {
    @get:OutputDirectory
    abstract val generatedDirectory: DirectoryProperty

    init {
        into(generatedDirectory)
    }
}

plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.kotlin.serialization)
    id("kotlin-parcelize")
}

@Suppress("UnstableApiUsage")
android {
    namespace = "com.lidesheng.hyperlyric"
    buildToolsVersion = "37.0.0"
    compileSdk {
        version = release(37) {
            minorApiLevel = 0
        }
    }

    defaultConfig {
        minSdk = 36
        buildConfigField("boolean", "ONLINE_FEATURES_ENABLED", "true")
        // These fields are generated by HyperLyric's application module. The port is a library,
        // so retain the upstream version identity while binding package-sensitive calls to this host.
        buildConfigField("int", "VERSION_CODE", "1937")
        buildConfigField("String", "VERSION_NAME", "\"7.2\"")
        buildConfigField("String", "APPLICATION_ID", "\"io.github.superisland\"")
    }

    buildFeatures {
        aidl = true
        buildConfig = true
        compose = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
}

dependencies {
    implementation(project(":source-lyric"))
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.constraintlayout.compose)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.palette.ktx)
    implementation(libs.androidx.compose.animation.graphics)
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.compose.foundation)
    implementation(libs.hiddenapibypass)
    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.libxposed.service)
    implementation(libs.miuix.blur)
    implementation(libs.miuix.icons)
    implementation(libs.miuix.nav)
    implementation(libs.miuix.preference)
    implementation(libs.miuix.ui)
    implementation(libs.okhttp)
    implementation(libs.reorderable)
    implementation(libs.retrofit)
    implementation(libs.retrofit.kotlinx.serialization.converter)
    implementation(libs.shizuku.api)
    implementation(libs.shizuku.provider)
    implementation(libs.superlyric.api)
    implementation(libs.lyricon.subscriber)
    implementation(libs.daimajia.animations) { artifact { type = "aar" } }
    implementation(libs.daimajia.easing) { artifact { type = "aar" } }
    compileOnly(libs.libxposed.api)
}

val hyperLyricReferenceCommit = "618e500b6661ad5232092cd4599f5d47f2365d9c"
val superIslandUpstreamsDir =
    providers.gradleProperty("superIslandUpstreamsDir")
        .orElse(providers.environmentVariable("SUPER_ISLAND_UPSTREAMS_DIR"))
        .orElse("${System.getProperty("user.home")}/.cache/super-island/upstreams")
        .map(::file)
val hyperLyricCheckout = superIslandUpstreamsDir.get().resolve("HyperLyric")
val hyperLyricMainRoot = hyperLyricCheckout.resolve("app/src/main")
val hyperLyricSourceRoot = hyperLyricMainRoot.resolve("java")
val hyperLyricOnlineSourceRoot = hyperLyricCheckout.resolve("app/src/online/java")
val hyperLyricExcludesFile = layout.projectDirectory.file("hyperlyric-excludes.txt")
val hyperLyricExcludedSources =
    hyperLyricExcludesFile.asFile.readLines()
        .map(String::trim)
        .filter { it.isNotEmpty() && !it.startsWith("#") }
        .toSet()
// Super Island owns the only user-facing settings surface. These are HyperLyric application
// lifecycle/configuration classes, not its SystemUI runtime, so they must never be generated.
val hyperLyricApplicationOnlySources = setOf(
    "common/PrefsBridge.kt",
    "lyric/ConfigRepository.kt",
    "root/RootApplication.kt",
    "utils/BackupRestoreManager.kt",
    "utils/LyricProviderManager.kt",
)
// The media-card preview is a functional settings component. It remains generated from the
// fixed upstream source while the surrounding HyperLyric settings pages stay excluded.
val hyperLyricPreviewSources = setOf(
    "ui/anim/MediaAlbumArtModifiers.kt",
    "ui/page/hooksettings/media/preview/MediaPreviewCard.kt",
    "ui/page/hooksettings/media/preview/PreviewMediaStyleConfig.kt",
)
val hyperLyricAppUiExcludedSources =
    hyperLyricSourceRoot.resolve("com/lidesheng/hyperlyric/ui").walkTopDown()
        .filter { it.isFile && it.extension == "kt" }
        .map { it.relativeTo(hyperLyricSourceRoot.resolve("com/lidesheng/hyperlyric")).invariantSeparatorsPath }
        .filterNot { it in hyperLyricPreviewSources }
        .toSet()
val hyperLyricPreviewResources = setOf(
    "drawable-xxhdpi/media_album_cover_1.jpg",
    "drawable-xxhdpi/media_album_cover_2.jpg",
    "drawable-xxhdpi/media_app_icon.png",
    "drawable-xxhdpi/preview_bg_soft_dark_1.png",
    "drawable-xxhdpi/preview_bg_soft_light_1.png",
    "drawable-xxhdpi/preview_bg_soft_dark_2.png",
    "drawable-xxhdpi/preview_bg_soft_light_2.png",
    "drawable-nodpi/preview_flow_dark.jpg",
    "drawable-nodpi/preview_flow_light.jpg",
    "drawable/ic_media_seamless.xml",
    "drawable/ic_media_fav.xml",
    "drawable/ic_media_prev.xml",
    "drawable/ic_media_play.xml",
    "drawable/ic_media_pause.xml",
    "drawable/ic_media_next.xml",
    "drawable/ic_media_lyric.xml",
)
// Every generated upstream source must remain byte-for-byte identical unless this small,
// audited set needs the current module's LSPosed service or preferences owner.
val hyperLyricPortAdaptedSources = setOf(
    "common/media/MediaMetadataHelper.kt",
    "root/HookEntry.kt",
    "root/UnlockIslandWhitelist.kt",
    "root/mediacard/MediaCardRuntimeConfig.kt",
    "root/mediacard/notification/NotificationMediaAmbientFlowHooker.kt",
    "root/mediacard/notification/NotificationMediaCoverStyleHooker.kt",
    "root/mediacard/notification/background/NotificationMediaBackgroundController.kt",
    "root/island/effects/album/IslandAlbumCoverStyleHooker.kt",
    "root/island/effects/color/IslandMusicWaveColorHooker.kt",
    "root/island/effects/glow/HookIslandGlow.kt",
    "root/media/CurrentMediaInfoResolver.kt",
    "utils/LogManager.kt",
)
val hyperLyricAppUiSourcePrefix = "ui/"
fun isHyperLyricPortExcludedSource(relativePath: String): Boolean =
    relativePath in hyperLyricExcludedSources ||
        relativePath in hyperLyricApplicationOnlySources ||
        (relativePath.startsWith(hyperLyricAppUiSourcePrefix) &&
            relativePath !in hyperLyricPreviewSources)
val hyperLyricGeneratedSourceDir = layout.buildDirectory.dir("generated/source/hyperlyric")
val hyperLyricGeneratedAidlDir = layout.buildDirectory.dir("generated/aidl/hyperlyric")
val hyperLyricGeneratedResDir = layout.buildDirectory.dir("generated/res/hyperlyric")

val verifyHyperLyricReference = tasks.register("verifyHyperLyricReference") {
    group = "verification"
    description = "Verifies the fixed HyperLyric checkout before source and values generation."
    dependsOn(rootProject.tasks.named("verifyPinnedUpstreams"))
    inputs.file(hyperLyricExcludesFile)
    inputs.dir(hyperLyricCheckout)
    doLast {
        val commit = providers.exec {
            commandLine("git", "-C", hyperLyricCheckout.absolutePath, "rev-parse", "HEAD")
        }.standardOutput.asText.get().trim()
        check(commit == hyperLyricReferenceCommit) {
            "HyperLyric reference mismatch: expected $hyperLyricReferenceCommit, got $commit"
        }
        check(hyperLyricExcludedSources.size == 8) {
            "HyperLyric exclusions changed without review: $hyperLyricExcludedSources"
        }
        check(
            hyperLyricExcludedSources.all {
                hyperLyricSourceRoot.resolve("com/lidesheng/hyperlyric/$it").isFile
            },
        ) {
            "HyperLyric exclusion is not a source file: $hyperLyricExcludedSources"
        }
        check(
            hyperLyricApplicationOnlySources.all {
                hyperLyricSourceRoot.resolve("com/lidesheng/hyperlyric/$it").isFile
            },
        ) {
            "HyperLyric application-only source is not a source file: $hyperLyricApplicationOnlySources"
        }
    }
}

val generateHyperLyricPortSource = tasks.register<GeneratedHyperLyricSync>("generateHyperLyricPortSource") {
    dependsOn(verifyHyperLyricReference)
    generatedDirectory.set(hyperLyricGeneratedSourceDir)
    from(hyperLyricSourceRoot) {
        include("**/*.kt")
        (hyperLyricExcludedSources + hyperLyricApplicationOnlySources + hyperLyricAppUiExcludedSources)
            .forEach { excluded ->
            exclude("com/lidesheng/hyperlyric/$excluded")
        }
    }
    // HyperLyric's default app flavor is online; use that exact source set rather than a local
    // lyric-provider substitute.
    from(hyperLyricOnlineSourceRoot) {
        include("**/*.kt")
    }
    doLast {
        val generatedRoot = hyperLyricGeneratedSourceDir.get().asFile
        val sourceRoot = hyperLyricSourceRoot.resolve("com/lidesheng/hyperlyric")
        val expectedSources = sourceRoot.walkTopDown()
            .filter { it.isFile && it.extension == "kt" }
            .map { it.relativeTo(sourceRoot).invariantSeparatorsPath }
            .filterNot(::isHyperLyricPortExcludedSource)
            .toMutableSet()
            .apply {
                addAll(
                    hyperLyricOnlineSourceRoot.resolve("com/lidesheng/hyperlyric").walkTopDown()
                        .filter { it.isFile && it.extension == "kt" }
                        .map { it.relativeTo(hyperLyricOnlineSourceRoot.resolve("com/lidesheng/hyperlyric")).invariantSeparatorsPath },
                )
            }
        val generatedSources = generatedRoot.resolve("com/lidesheng/hyperlyric").walkTopDown()
            .filter { it.isFile && it.extension == "kt" }
            .map { it.relativeTo(generatedRoot.resolve("com/lidesheng/hyperlyric")).invariantSeparatorsPath }
            .toSet()
        check(generatedSources == expectedSources) {
            "HyperLyric generated source set changed; missing=${expectedSources - generatedSources}, " +
                "unexpected=${generatedSources - expectedSources}"
        }
        check(
            (hyperLyricExcludedSources + hyperLyricApplicationOnlySources).none {
                generatedRoot.resolve("com/lidesheng/hyperlyric/$it").exists()
            },
        ) {
            "Excluded HyperLyric source was generated"
        }
        check(
            generatedSources
                .filter { it.startsWith(hyperLyricAppUiSourcePrefix) }
                .toSet() == hyperLyricPreviewSources,
        ) {
            "Unexpected HyperLyric App UI source was generated"
        }
        val visualResourceReferences = generatedRoot.walkTopDown()
            .filter { it.isFile && it.extension == "kt" }
            .filter { source ->
                Regex("""R\.(drawable|mipmap|xml|font|raw)\.""").containsMatchIn(source.readText())
            }
            .map { it.relativeTo(generatedRoot).invariantSeparatorsPath }
            .toList()
        check(
            visualResourceReferences.toSet() ==
                setOf("com/lidesheng/hyperlyric/ui/page/hooksettings/media/preview/MediaPreviewCard.kt"),
        ) {
            "HyperLyric source has an unexpected visual-resource dependency: $visualResourceReferences"
        }

        // Explicit feature removals approved for this port: Live Update and its Focus-whitelist
        // hook must not remain reachable after their source files are excluded.
        val hookEntry = generatedRoot.resolve("com/lidesheng/hyperlyric/root/HookEntry.kt")
        val originalHookEntry = hookEntry.readText()
        val hookCall = """                UnlockFocusWhitelist.hook(this, param.defaultClassLoader)
"""
        check(originalHookEntry.contains(hookCall)) { "HyperLyric HookEntry whitelist call changed" }
        val withoutFocusWhitelist = originalHookEntry.replace(hookCall, "")
        val runtimeField = """    private var runtimeApp: Application? = null
"""
        check(withoutFocusWhitelist.contains(runtimeField)) {
            "HyperLyric HookEntry runtime field changed"
        }
        val portRuntimeField = """    private var portHostModule: XposedModule? = null
"""
        val companionClose = """        )
    }

    private var _prefs: android.content.SharedPreferences? = null
"""
        check(withoutFocusWhitelist.contains(companionClose)) {
            "HyperLyric HookEntry companion boundary changed"
        }
        val portBinding = """        )

        private val portSystemUiHookedClassLoaders = java.util.Collections.synchronizedSet(
            java.util.Collections.newSetFromMap(java.util.WeakHashMap<ClassLoader, Boolean>())
        )

        /** Supplies the host adapter before the unmodified upstream load chain runs. */
        @JvmStatic
        fun preparePortRuntime(
            module: XposedModule,
            preferences: android.content.SharedPreferences,
            classLoader: ClassLoader
        ) {
            val runtime = instance ?: HookEntry().also { instance = it }
            runtime.portHostModule = module
            runtime._prefs = preferences
            HookLogger.module = module
            installPortSystemUiRuntime(module, classLoader)
        }

        /**
         * Runs the full SystemUI branch from HookEntry.onPackageLoaded with the existing
         * Super Island module as the only hook-handle owner.
         */
        @JvmStatic
        fun installPortSystemUiRuntime(module: XposedModule, classLoader: ClassLoader) {
            val runtime = instance ?: return
            if (!portSystemUiHookedClassLoaders.add(classLoader)) return

            StatusBarTextColorHooker.setTextColorChangedListener {
                BaseIslandRenderer.updateTextColors()
            }
            StatusBarTextColorHooker.hook(module, classLoader)
            MediaCardRuntimeConfig.load(runtime.prefs)
            val mediaCardConfig = MediaCardRuntimeConfig.current
            if (mediaCardConfig.enabled) {
                MediaCardConfigurationRefreshHooker.hook(module, classLoader)
                MediaProgressStyleHooker.hook(module, classLoader)
                if (shouldInstallMediaCardElementBehavior(mediaCardConfig)) {
                    MediaCardElementBehaviorHooker.hook(module, classLoader)
                } else {
                    HookLogger.d(TAG, "媒体卡片封面行为均为原生，跳过封面行为 Hook")
                }
                IslandExpandedMediaAmbientFlowHooker.hook(module, classLoader)
                IslandExpandedMediaLayoutHooker.hook(module, classLoader)
                if (shouldInstallNotificationMediaRendering(mediaCardConfig)) {
                    NotificationMediaAmbientFlowHooker.hook(module, classLoader)
                } else {
                    HookLogger.d(TAG, "通知中心媒体渲染均为原生，跳过渲染 Hook")
                }
                NotificationMediaCoverStyleHooker.hook(module, classLoader)
                if (mediaCardConfig.notification.cardSwitcherEnabled) {
                    NotificationMediaSingleCardSwitcherHooker.hook(module, classLoader)
                } else {
                    HookLogger.d(TAG, "通知中心多媒体卡片切换功能未启用，跳过媒体卡片切换 Hook")
                }
                try {
                    UnlockIslandWhitelist.hook(module, classLoader)
                } catch (e: Exception) {
                    if (e is ClassNotFoundException || e is NoSuchMethodException) {
                        HookLogger.w(TAG, "此系统版本不支持超级岛下拉小窗白名单")
                    } else {
                        HookLogger.e(TAG, "超级岛下拉小窗白名单注入失败", e)
                    }
                }
            } else {
                HookLogger.d(TAG, "媒体卡片总开关关闭，跳过全部媒体卡片 Hook")
            }
            activeMode = runtime.prefs.getInt(
                RootConstants.KEY_HOOK_LYRIC_MODE,
                RootConstants.DEFAULT_HOOK_LYRIC_MODE
            )

            // 劫持 Application.onCreate 以初始化 Lyricon Receiver 所需的环境
            try {
                val appClass = classLoader.loadClass("android.app.Application")
                val onCreateMethod = appClass.getDeclaredMethod("onCreate")
                module.deoptimize(onCreateMethod)
                module.hook(onCreateMethod).intercept(AppCreateHooker())
            } catch (e: Exception) {
                if (e is ClassNotFoundException || e is NoSuchMethodException) {
                    HookLogger.w(TAG, "跳过生命周期 Hook: target=Application.onCreate")
                } else {
                    HookLogger.e(
                        TAG,
                        "安装生命周期 Hook 失败: target=Application.onCreate",
                        e
                    )
                }
            }

            // 核心：拦截 ClassLoader 构造，以捕捉 miui.systemui.plugin 等动态加载的插件
            try {
                val clClass = Class.forName("dalvik.system.BaseDexClassLoader")
                for (constructor in clClass.declaredConstructors) {
                    module.deoptimize(constructor)
                    module.hook(constructor).intercept(runtime.ClassLoaderHooker())
                }
            } catch (e: Exception) {
                if (e is ClassNotFoundException || e is NoSuchMethodException) {
                    HookLogger.w(TAG, "跳过插件加载 Hook: target=BaseDexClassLoader")
                } else {
                    HookLogger.e(
                        TAG,
                        "安装插件加载 Hook 失败: target=BaseDexClassLoader",
                        e
                    )
                }
            }
        }

        /**
         * These two upstream hooks deoptimize methods invoked by every media-card
         * transition. Install them only when their owned behavior is selected.
         */
        private fun shouldInstallMediaCardElementBehavior(
            config: MediaCardRuntimeConfig.Snapshot
        ): Boolean =
            config.enabled && (
                config.notification.hideCoverShadow ||
                    config.notification.disableCoverFlip ||
                    config.islandExpanded.disableCoverFlip
                )

        /**
         * The notification renderer owns flow, card theme, and custom background.
         * Its all-native state must leave SystemUI's bind, draw, and click paths untouched.
         */
        private fun shouldInstallNotificationMediaRendering(
            config: MediaCardRuntimeConfig.Snapshot
        ): Boolean =
            config.enabled && (
                config.notification.ambientFlowMode !=
                    RootConstants.NOTIFICATION_MEDIA_AMBIENT_FLOW_MODE_DISABLED ||
                    config.notification.cardTheme != RootConstants.MEDIA_CARD_THEME_FOLLOW_SYSTEM ||
                    config.notification.backgroundStyle !=
                        RootConstants.NOTIFICATION_MEDIA_BACKGROUND_STYLE_DEFAULT
                )
    }

    private var _prefs: android.content.SharedPreferences? = null
"""
        val withPortRuntime = withoutFocusWhitelist
            .replace(runtimeField, runtimeField + portRuntimeField)
            .replace(companionClose, portBinding)
            .replace(
                """                SystemUIHookRegistry.hook(this@HookEntry, cl, lyricsOnly = lyricsOnly)
""",
                """                SystemUIHookRegistry.hook(portHostModule ?: this@HookEntry, cl, lyricsOnly = lyricsOnly)
""",
            )
            .replace(
                """            if (SystemUiEnhancementGate.isEnabled()) {
                sourceManager?.start()
            }
""",
                """            if (SystemUiEnhancementGate.isEnabled() &&
                prefs.getString(
                    RootConstants.KEY_HOOK_LYRIC_SOURCE,
                    RootConstants.DEFAULT_HOOK_LYRIC_SOURCE
                ) != "media_fallback"
            ) {
                sourceManager?.start()
            }
""",
            )
            .replace(
                """                            Handler(Looper.getMainLooper()).post {
                                val manager = sourceManager
                                manager?.switchSource(newSourceId)
                                val activeSourceId = manager?.getActiveSource()?.id
                                if (activeSourceId == newSourceId) {
                                    HookLogger.i(TAG, "歌词源切换完成: source=${'$'}newSourceId")
                                }
                            }
""",
                """                            Handler(Looper.getMainLooper()).post {
                                val manager = sourceManager
                                if (newSourceId == "media_fallback") {
                                    manager?.stop()
                                    HookLogger.i(TAG, "歌词源切换完成: source=${'$'}newSourceId")
                                } else {
                                    manager?.switchSource(newSourceId)
                                    val activeSourceId = manager?.getActiveSource()?.id
                                    if (activeSourceId == newSourceId) {
                                        HookLogger.i(TAG, "歌词源切换完成: source=${'$'}newSourceId")
                                    }
                                }
                            }
""",
            )
            .replace(
                """        if (enabled) {
            sourceManager?.start()
            IslandSettingsRefreshCoordinator.request()
""",
                """        if (enabled) {
            if (prefs.getString(
                    RootConstants.KEY_HOOK_LYRIC_SOURCE,
                    RootConstants.DEFAULT_HOOK_LYRIC_SOURCE
                ) != "media_fallback"
            ) {
                sourceManager?.start()
            }
            IslandSettingsRefreshCoordinator.request()
""",
            )
        check(withPortRuntime.contains("preparePortRuntime(")) {
            "HyperLyric HookEntry port binding was not generated"
        }
        check(withPortRuntime.contains("SystemUIHookRegistry.hook(portHostModule ?: this@HookEntry")) {
            "HyperLyric ClassLoader hook host binding changed"
        }
        hookEntry.writeText(withPortRuntime)

        // These upstream effect owners receive the host's registered XposedModule. In this port
        // that instance is SuperIslandXposedModule rather than HookEntry, while HookEntry.instance
        // remains the upstream owner of the bound RemotePreferences. Keep every effect algorithm
        // intact and adapt only that host-instance lookup.
        fun replacePortPreferenceOwner(
            relativePath: String,
            original: String,
            replacement: String,
        ) {
            val file = generatedRoot.resolve("com/lidesheng/hyperlyric/$relativePath")
            val source = file.readText()
            check(source.contains(original)) {
                "HyperLyric port preference owner changed: $relativePath"
            }
            file.writeText(source.replace(original, replacement))
        }
        replacePortPreferenceOwner(
            relativePath = "root/island/effects/album/IslandAlbumCoverStyleHooker.kt",
            original = "get() = (module as? HookEntry)?.prefs",
            replacement = "get() = HookEntry.instance?.prefs",
        )
        replacePortPreferenceOwner(
            relativePath = "root/island/effects/color/IslandMusicWaveColorHooker.kt",
            original = "get() = (module as? HookEntry)?.prefs",
            replacement = "get() = HookEntry.instance?.prefs",
        )
        replacePortPreferenceOwner(
            relativePath = "root/island/effects/glow/HookIslandGlow.kt",
            original = "get() = if (::module.isInitialized) (module as? HookEntry)?.prefs else null",
            replacement = "get() = if (::module.isInitialized) HookEntry.instance?.prefs else null",
        )
        replacePortPreferenceOwner(
            relativePath = "root/UnlockIslandWhitelist.kt",
            original = "val prefs = (module as HookEntry).prefs",
            replacement = "val prefs = HookEntry.instance?.prefs ?: return",
        )
        replacePortPreferenceOwner(
            relativePath = "root/UnlockIslandWhitelist.kt",
            original = "val prefs = (module as? HookEntry)?.prefs ?: return",
            replacement = "val prefs = HookEntry.instance?.prefs ?: return",
        )

        // The upstream snapshot permanently enables media cards. The host has a separate
        // master switch, so only this preference read is adapted; absent keys preserve the
        // upstream enabled default for existing installations.
        fun replacePortSource(
            relativePath: String,
            original: String,
            replacement: String,
        ) {
            val file = generatedRoot.resolve("com/lidesheng/hyperlyric/$relativePath")
            val source = file.readText()
            check(source.contains(original)) {
                "HyperLyric port source changed: $relativePath"
            }
            file.writeText(source.replace(original, replacement))
        }
        replacePortSource(
            relativePath = "root/mediacard/MediaCardRuntimeConfig.kt",
            original = "            fun from(prefs: SharedPreferences) = Snapshot(\n                enabled = true,\n",
            replacement = "            fun from(prefs: SharedPreferences) = Snapshot(\n                enabled = prefs.getBoolean(\"key_hook_media_card_enabled\", true),\n",
        )

        // Keep the upstream visual algorithms and cache keys intact, but avoid repeating their
        // structural mutations for the same controller state on every SystemUI bind callback.
        replacePortSource(
            relativePath = "root/mediacard/notification/NotificationMediaAmbientFlowHooker.kt",
            original = "        val isPlaying = readField(mediaData, \"isPlaying\") == true\n        state.isPlaying = isPlaying\n        configureCustomView(state)\n        syncPlayback(state)\n",
            replacement = "        val isPlaying = readField(mediaData, \"isPlaying\") == true\n        val playbackChanged = !state.playbackConfigured || state.isPlaying != isPlaying\n        state.isPlaying = isPlaying\n        if (playbackChanged) {\n            configureCustomView(state)\n            syncPlayback(state)\n            state.playbackConfigured = true\n        }\n",
        )
        replacePortSource(
            relativePath = "root/mediacard/notification/NotificationMediaAmbientFlowHooker.kt",
            original = "        var hasColors: Boolean = false,\n        val colorRequest: AtomicInteger = AtomicInteger()\n",
            replacement = "        var hasColors: Boolean = false,\n        var playbackConfigured: Boolean = false,\n        val colorRequest: AtomicInteger = AtomicInteger()\n",
        )
        replacePortSource(
            relativePath = "root/mediacard/notification/NotificationMediaAmbientFlowHooker.kt",
            original = "    private data class ControllerThemeState(val originalContext: Context)\n",
            replacement = "    private data class ControllerThemeState(\n        val originalContext: Context,\n        val appliedTheme: Int\n    )\n",
        )
        replacePortSource(
            relativePath = "root/mediacard/notification/NotificationMediaAmbientFlowHooker.kt",
            original = "            val existingState = themeStates[controller]\n            val originalContext = existingState?.originalContext\n                ?: contextField.get(controller) as Context\n",
            replacement = "            val existingState = themeStates[controller]\n            if (existingState?.appliedTheme == theme ||\n                theme == RootConstants.MEDIA_CARD_THEME_FOLLOW_SYSTEM && existingState == null\n            ) {\n                return\n            }\n            val originalContext = existingState?.originalContext\n                ?: contextField.get(controller) as Context\n",
        )
        replacePortSource(
            relativePath = "root/mediacard/notification/NotificationMediaAmbientFlowHooker.kt",
            original = "                themeStates[controller] = ControllerThemeState(originalContext)\n",
            replacement = "                themeStates[controller] = ControllerThemeState(originalContext, theme)\n",
        )

        replacePortSource(
            relativePath = "root/mediacard/notification/NotificationMediaCoverStyleHooker.kt",
            original = "    private val boundSessionIdentities =\n        Collections.synchronizedMap(WeakHashMap<Any, String>())\n",
            replacement = "    private val boundSessionIdentities =\n        Collections.synchronizedMap(WeakHashMap<Any, String>())\n    private val appliedStyleSignatures =\n        Collections.synchronizedMap(WeakHashMap<Any, StyleSignature>())\n    private val appliedLayoutSignatures =\n        Collections.synchronizedMap(WeakHashMap<Any, LayoutSignature>())\n",
        )
        replacePortSource(
            relativePath = "root/mediacard/notification/NotificationMediaCoverStyleHooker.kt",
            original = "            if (methodName == \"detach\") {\n                boundSessionIdentities.remove(controller)\n                cleanupStyle(controller)\n",
            replacement = "            if (methodName == \"detach\") {\n                boundSessionIdentities.remove(controller)\n                appliedStyleSignatures.remove(controller)\n                appliedLayoutSignatures.remove(controller)\n                cleanupStyle(controller)\n",
        )
        replacePortSource(
            relativePath = "root/mediacard/notification/NotificationMediaCoverStyleHooker.kt",
            original = "    private fun applyStyle(controller: Any, mediaData: Any?) {\n        val api = resolveApi(controller.javaClass.classLoader) ?: return\n        val holder = api.getHolder(controller) ?: return\n        val albumView = api.getAlbumView(holder)\n        val albumImage = api.getAlbumImage(holder)\n        val config = runtimeConfig.notification\n        val layoutStyle = config.layoutStyle\n",
            replacement = "    private fun applyStyle(controller: Any, mediaData: Any?) {\n        val api = resolveApi(controller.javaClass.classLoader) ?: return\n        val holder = api.getHolder(controller) ?: return\n        val albumView = api.getAlbumView(holder)\n        val albumImage = api.getAlbumImage(holder)\n        val config = runtimeConfig.notification\n        val layoutStyle = config.layoutStyle\n        val currentMediaData = api.getMediaData(controller) ?: mediaData\n        val signature = StyleSignature(\n            holder = holder,\n            mediaIdentity = NotificationMediaDataIdentity.of(currentMediaData),\n            config = config,\n        )\n        if (appliedStyleSignatures[controller] == signature) {\n            syncRotatingCover(api, controller, albumImage, mediaData)\n            return\n        }\n",
        )
        replacePortSource(
            relativePath = "root/mediacard/notification/NotificationMediaCoverStyleHooker.kt",
            original = "        }\n    }\n\n    private fun applyExpandedMediaSeekBarPadding(seekBar: View) {\n",
            replacement = "        }\n        appliedStyleSignatures[controller] = signature\n    }\n\n    private fun syncRotatingCover(\n        api: NotificationMediaHostApi,\n        controller: Any,\n        albumImage: ImageView,\n        mediaData: Any?\n    ) {\n        val config = runtimeConfig.notification\n        val unsupportedLayout = config.layoutStyle ==\n            RootConstants.NOTIFICATION_MEDIA_LAYOUT_STYLE_ONEUI ||\n            config.layoutStyle == RootConstants.NOTIFICATION_MEDIA_LAYOUT_STYLE_MIUI ||\n            config.layoutStyle == RootConstants.NOTIFICATION_MEDIA_LAYOUT_STYLE_PIXEL\n        if (!unsupportedLayout &&\n            config.coverStyle == RootConstants.NOTIFICATION_MEDIA_COVER_STYLE_ROTATING_CIRCLE\n        ) {\n            MediaCoverRotationController.attach(\n                albumImage,\n                api.isPlaying(api.getMediaData(controller) ?: mediaData)\n            )\n        }\n    }\n\n    private data class StyleSignature(\n        val holder: Any,\n        val mediaIdentity: String,\n        val config: MediaCardRuntimeConfig.Notification,\n    )\n\n    private data class LayoutSignature(\n        val layout: Any,\n        val config: MediaCardRuntimeConfig.Notification,\n        val uiMode: Int,\n    )\n\n    private fun applyExpandedMediaSeekBarPadding(seekBar: View) {\n",
        )
        replacePortSource(
            relativePath = "root/mediacard/notification/NotificationMediaCoverStyleHooker.kt",
            original = "    private fun applyLoadedLayout(api: NotificationMediaHostApi, controller: Any) {\n        val config = runtimeConfig.notification\n        val normalLayout = api.getNormalLayout(controller) ?: return\n        val context = api.getLayoutContext(controller)\n        NotificationMediaLayoutController.apply(\n",
            replacement = "    private fun applyLoadedLayout(api: NotificationMediaHostApi, controller: Any) {\n        val config = runtimeConfig.notification\n        val normalLayout = api.getNormalLayout(controller) ?: return\n        val context = api.getLayoutContext(controller)\n        val signature = LayoutSignature(\n            layout = normalLayout,\n            config = config,\n            uiMode = context.resources.configuration.uiMode,\n        )\n        if (appliedLayoutSignatures[controller] == signature) return\n        NotificationMediaLayoutController.apply(\n",
        )
        replacePortSource(
            relativePath = "root/mediacard/notification/NotificationMediaCoverStyleHooker.kt",
            original = "            actionsOrder = config.actionOrder\n        )\n    }\n\n    private data class ColorOsAppIconState(\n",
            replacement = "            actionsOrder = config.actionOrder\n        )\n        appliedLayoutSignatures[controller] = signature\n    }\n\n    private data class ColorOsAppIconState(\n",
        )

        replacePortSource(
            relativePath = "root/mediacard/notification/background/NotificationMediaBackgroundController.kt",
            original = "                applyBackground(mediaBg, rendered.bitmap)\n                NotificationMediaForegroundStyler.apply(controller, holder, rendered.colors)\n                state.customApplied = true\n                state.appliedToken = token\n                state.artworkFingerprint = rendered.artworkFingerprint\n                state.renderPending = false\n",
            replacement = "                scheduleBackgroundApply(\n                    controller = controller,\n                    state = state,\n                    mediaBg = mediaBg,\n                    holder = holder,\n                    rendered = rendered,\n                    token = token,\n                    style = style,\n                    request = request,\n                    width = width,\n                    height = height,\n                )\n",
        )
        replacePortSource(
            relativePath = "root/mediacard/notification/background/NotificationMediaBackgroundController.kt",
            original = "    private fun applyBackground(mediaBg: ImageView, bitmap: Bitmap) {\n",
            replacement = "    private fun scheduleBackgroundApply(\n        controller: Any,\n        state: ControllerState,\n        mediaBg: ImageView,\n        holder: Any,\n        rendered: RenderedNotificationMediaBackground,\n        token: String,\n        style: Int,\n        request: Int,\n        width: Int,\n        height: Int,\n    ) {\n        state.pendingApply?.rendered?.bitmap?.recycle()\n        state.pendingApply = PendingApply(\n            mediaBg = mediaBg,\n            holder = holder,\n            rendered = rendered,\n            token = token,\n            style = style,\n            request = request,\n            width = width,\n            height = height,\n        )\n        schedulePendingBackgroundApply(controller, state)\n    }\n\n    private fun schedulePendingBackgroundApply(controller: Any, state: ControllerState) {\n        if (state.applyScheduled) return\n        val mediaBg = state.pendingApply?.mediaBg ?: return\n        state.applyScheduled = true\n        mediaBg.postOnAnimation {\n            state.applyScheduled = false\n            val pending = state.pendingApply ?: return@postOnAnimation\n            if (\n                states[controller] !== state || state.request.get() != pending.request ||\n                currentStyle() != pending.style || !isActive(controller)\n            ) {\n                state.pendingApply = null\n                pending.rendered.bitmap.recycle()\n                return@postOnAnimation\n            }\n            val width = mediaBg.width\n            val height = mediaBg.height\n            if (width != pending.width || height != pending.height) {\n                state.pendingApply = null\n                pending.rendered.bitmap.recycle()\n                state.renderPending = false\n                state.lastMediaData?.let { data ->\n                    mediaBg.postOnAnimation {\n                        if (states[controller] === state) onBind(controller, data)\n                    }\n                }\n                return@postOnAnimation\n            }\n            if (!mediaBg.isLaidOut || mediaBg.isLayoutRequested || pending.stableFrames++ == 0) {\n                schedulePendingBackgroundApply(controller, state)\n                return@postOnAnimation\n            }\n            state.pendingApply = null\n            applyBackground(mediaBg, pending.rendered.bitmap)\n            NotificationMediaForegroundStyler.apply(controller, pending.holder, pending.rendered.colors)\n            state.customApplied = true\n            state.appliedToken = pending.token\n            state.artworkFingerprint = pending.rendered.artworkFingerprint\n            state.renderPending = false\n        }\n    }\n\n    private fun applyBackground(mediaBg: ImageView, bitmap: Bitmap) {\n",
        )
        replacePortSource(
            relativePath = "root/mediacard/notification/background/NotificationMediaBackgroundController.kt",
            original = "        states.remove(controller)?.let { state ->\n            state.request.incrementAndGet()\n            restoreMediaBackground(state)\n",
            replacement = "        states.remove(controller)?.let { state ->\n            state.request.incrementAndGet()\n            state.pendingApply?.rendered?.bitmap?.recycle()\n            state.pendingApply = null\n            restoreMediaBackground(state)\n",
        )
        replacePortSource(
            relativePath = "root/mediacard/notification/background/NotificationMediaBackgroundController.kt",
            original = "        var layoutRetryScheduled: Boolean = false,\n        val request: AtomicInteger = AtomicInteger()\n    )\n",
            replacement = "        var layoutRetryScheduled: Boolean = false,\n        var pendingApply: PendingApply? = null,\n        var applyScheduled: Boolean = false,\n        val request: AtomicInteger = AtomicInteger()\n    )\n\n    private data class PendingApply(\n        val mediaBg: ImageView,\n        val holder: Any,\n        val rendered: RenderedNotificationMediaBackground,\n        val token: String,\n        val style: Int,\n        val request: Int,\n        val width: Int,\n        val height: Int,\n        var stableFrames: Int = 0,\n    )\n",
        )

        // Some media controllers expose a stable title through the standard custom metadata
        // field while updating TITLE and DISPLAY_TITLE with lyric text. Keep the complete
        // upstream fallback order when that optional field is absent.
        val mediaMetadataHelper = generatedRoot.resolve(
            "com/lidesheng/hyperlyric/common/media/MediaMetadataHelper.kt"
        )
        val originalMediaMetadataHelper = mediaMetadataHelper.readText()
        val mediaInfoTitleField = """        val title: String = "",
"""
        check(originalMediaMetadataHelper.contains(mediaInfoTitleField)) {
            "HyperLyric MediaInfo title field changed"
        }
        val mediaInfoWithCustomTitleField = """        val title: String = "",
        val customTitle: String? = null,
"""
        val mediaInfoBuilder = """        val mediaDescription = description
        val artwork = extractAlbumArt()
        return MediaInfo(
            title = getString(MediaMetadata.METADATA_KEY_TITLE)
                ?: getString(MediaMetadata.METADATA_KEY_DISPLAY_TITLE)
                ?: mediaDescription.title?.toString().orEmpty(),
"""
        check(originalMediaMetadataHelper.contains(mediaInfoBuilder)) {
            "HyperLyric MediaMetadata title fallback changed"
        }
        val mediaInfoBuilderWithCustomField = """        val mediaDescription = description
        val artwork = extractAlbumArt()
        val customTitle = getString("android.media.metadata.CUSTOM_FIELD_TITLE")
            ?.takeIf(String::isNotBlank)
        return MediaInfo(
            customTitle = customTitle,
            title = customTitle
                ?: getString(MediaMetadata.METADATA_KEY_TITLE)
                ?: getString(MediaMetadata.METADATA_KEY_DISPLAY_TITLE)
                ?: mediaDescription.title?.toString().orEmpty(),
"""
        val mediaMetadataWithCustomTitle = originalMediaMetadataHelper
            .replace(mediaInfoTitleField, mediaInfoWithCustomTitleField)
            .replace(mediaInfoBuilder, mediaInfoBuilderWithCustomField)
        check(mediaMetadataWithCustomTitle.contains("customTitle = getString(\"android.media.metadata.CUSTOM_FIELD_TITLE\")")) {
            "HyperLyric custom metadata title was not generated"
        }
        mediaMetadataHelper.writeText(mediaMetadataWithCustomTitle)

        val currentMediaInfoResolver = generatedRoot.resolve(
            "com/lidesheng/hyperlyric/root/media/CurrentMediaInfoResolver.kt"
        )
        val originalCurrentMediaInfoResolver = currentMediaInfoResolver.readText()
        val sourcePreferredTitle = """            title = sourceInfo.title ?: normalizeText(sessionInfo.title),
"""
        check(originalCurrentMediaInfoResolver.contains(sourcePreferredTitle)) {
            "HyperLyric current media title precedence changed"
        }
        val customTitlePreferred = """            title = sessionInfo.customTitle ?: sourceInfo.title ?: normalizeText(sessionInfo.title),
"""
        val currentMediaInfoResolverWithCustomTitle = originalCurrentMediaInfoResolver.replace(
            sourcePreferredTitle,
            customTitlePreferred,
        )
        check(currentMediaInfoResolverWithCustomTitle.contains(customTitlePreferred)) {
            "HyperLyric custom metadata title precedence was not generated"
        }
        currentMediaInfoResolver.writeText(currentMediaInfoResolverWithCustomTitle)

        val logManager = generatedRoot.resolve("com/lidesheng/hyperlyric/utils/LogManager.kt")
        val originalLogManager = logManager.readText()
        val readSection = "    // ========================= 读取 ========================="
        check(originalLogManager.contains(readSection)) {
            "HyperLyric LogManager read section changed"
        }
        // Log writing is used by the imported online/runtime code. Reading and rendering those
        // entries belongs to HyperLyric's App log page, which this port does not generate.
        logManager.writeText(
            originalLogManager
                .substringBefore(readSection)
                .replace("import com.lidesheng.hyperlyric.ui.page.log.LogEntry\n", "")
                .trimEnd() + "\n}\n",
        )

        val unexpectedMainSourceDifferences = sourceRoot.walkTopDown()
            .filter { it.isFile && it.extension == "kt" }
            .map { source ->
                val relativePath = source.relativeTo(sourceRoot).invariantSeparatorsPath
                relativePath to source
            }
            .filterNot { (relativePath, _) -> isHyperLyricPortExcludedSource(relativePath) }
            .filterNot { (relativePath, _) -> relativePath in hyperLyricPortAdaptedSources }
            .filter { (relativePath, source) ->
                generatedRoot.resolve("com/lidesheng/hyperlyric/$relativePath").readText() != source.readText()
            }
            .map { (relativePath, _) -> relativePath }
            .toList()
        check(unexpectedMainSourceDifferences.isEmpty()) {
            "HyperLyric source changed outside the audited host adapters: " +
                unexpectedMainSourceDifferences
        }

    }
}

val generateHyperLyricPortAidl = tasks.register<GeneratedHyperLyricSync>("generateHyperLyricPortAidl") {
    dependsOn(verifyHyperLyricReference)
    generatedDirectory.set(hyperLyricGeneratedAidlDir)
    from(hyperLyricMainRoot.resolve("aidl"))
}

val generateHyperLyricPortResources = tasks.register<GeneratedHyperLyricSync>("generateHyperLyricPortResources") {
    dependsOn(verifyHyperLyricReference)
    generatedDirectory.set(hyperLyricGeneratedResDir)
    // Only the assets directly referenced by the explicitly approved media-card preview are
    // packaged. Other upstream icons, screenshots, artwork, and App-page animation assets remain
    // excluded.
    from(hyperLyricMainRoot.resolve("res")) {
        include("values*/**/*.xml")
        hyperLyricPreviewResources.forEach(::include)
    }
    doLast {
        val expected = hyperLyricMainRoot.resolve("res").walkTopDown()
            .filter { it.isFile }
            .map { it.relativeTo(hyperLyricMainRoot.resolve("res")).invariantSeparatorsPath }
            .filter { it.startsWith("values") || it in hyperLyricPreviewResources }
            .toSet()
        val generated = hyperLyricGeneratedResDir.get().asFile.walkTopDown()
            .filter { it.isFile }
            .map { it.relativeTo(hyperLyricGeneratedResDir.get().asFile).invariantSeparatorsPath }
            .toSet()
        check(generated == expected) {
            "HyperLyric generated resources changed; missing=${expected - generated}, " +
                "unexpected=${generated - expected}"
        }
        check(
            generated.filter { it.startsWith("drawable") || it.startsWith("mipmap") || it.startsWith("xml") }
                .toSet() == hyperLyricPreviewResources,
        ) {
            "HyperLyric generated an unapproved visual or manifest resource: $generated"
        }
    }
}

// AGP 9's library SourceSet DSL has an incompatible runtime implementation. Register these
// generated directories through the supported variant source API so every variant is wired to
// the fixed upstream generation tasks without writing generated code into the worktree.
androidComponents {
    onVariants(selector().all()) { variant ->
        variant.sources.java?.addGeneratedSourceDirectory(
            generateHyperLyricPortSource,
            GeneratedHyperLyricSync::generatedDirectory,
        )
        variant.sources.kotlin?.addGeneratedSourceDirectory(
            generateHyperLyricPortSource,
            GeneratedHyperLyricSync::generatedDirectory,
        )
        variant.sources.aidl?.addGeneratedSourceDirectory(
            generateHyperLyricPortAidl,
            GeneratedHyperLyricSync::generatedDirectory,
        )
        variant.sources.res?.addGeneratedSourceDirectory(
            generateHyperLyricPortResources,
            GeneratedHyperLyricSync::generatedDirectory,
        )
    }
}

tasks.matching { it.name == "preBuild" }.configureEach {
    dependsOn(
        generateHyperLyricPortSource,
        generateHyperLyricPortAidl,
        generateHyperLyricPortResources,
    )
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    dependsOn(generateHyperLyricPortSource)
}
